# Generated by Django 4.1.1 on 2022-09-25 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_galery_alter_post_date_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='galery',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.post'),
        ),
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(upload_to='galery/', verbose_name='Изображение'),
        ),
    ]
