# Generated by Django 4.0.3 on 2022-09-25 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_galery_post_alter_galery_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galery',
        ),
    ]
