# Generated by Django 4.0.3 on 2022-09-26 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_galery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='image',
            field=models.ImageField(upload_to='galery', verbose_name='Изображение'),
        ),
    ]
